development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  # 「/1」が付いていると動かない
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379" } %>
  channel_prefix: sloppy_production
