default: &default
 adapter: mysql2
 encoding: utf8mb4
 charset: utf8mb4
 collation: utf8mb4_unicode_ci
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 username: root
 password:
 # socket: /var/lib/mysql/mysql.sock
 # socket: /var/run/mysqld/mysqld.sock # ubuntu用

development:
 <<: *default
 database: sloppy_development

test:
 <<: *default
 database: sloppy_test

production:
 <<: *default
 database: sloppy_production
 username: sloppy
 password: <%= ENV['SLOPPY_DATABASE_PASSWORD'] %>
 host: <%= ENV['SLOPPY_DATABASE_HOST'] %>
 port: 3306
